### ISSUE TITLE
Repeatedly placing and breaking Plump Helmets and Spindlestems allows unlimited generation of their seeds

### ISSUE THREAD

**Issue by alerikaisattera** [FaceDeer/dfcaverns#29]
Repeatedly placing and breaking Plump Helmets and Spindlestems allows unlimited generation of their seeds

**Comment by alerikaisattera** [comment]
Also applies to Dimple Cups

**Comment by FaceDeer** [comment]
Looks like this is a sign for me to come out of modding retirement . Been thinking about it for a while, but dfcaverns is an old favourite of mine and a slew of issues like this demands response. I'll fire up the ol' minetest machine and see if I can remember any of this LUA stuff. :)

**Comment by alerikaisattera** [comment]
Does not actually apply to Plump Helmets

**Comment by FaceDeer** [comment]
I've added a "sterile" harvested version of spindlestem caps and dimple cup that is dropped on harvest, this should prevent endless seed generation by placing and removing them.

Note that if players have any spindlestem cap in their inventory when this update is added to an existing game they'll need to place and re-harvest them to get them to work in their recipes.

**Comment by alerikaisattera** [comment]
Dimple Cups are still affected

**Comment by FaceDeer** [comment]
I can't see how, do you have the latest version of the code? I fixed dimple cup separately from spindlestems just a few hours ago. Now when you pick up a df_farming:dimple_cup_1 through _4 it should drop a df_farming:dimple_cup_harvested instead of a df_farming:dimple_cup_4, which cannot give further seeds when placed and picked up again.

If you had any df_farming:dimple_cup_4 in your inventory from before this fix went in then placing and picking them back up again will give you more seeds, but only once - they should become df_farming:dimple_cup_harvested after that.

**Comment by alerikaisattera** [comment]
Didn't see this
